### PR TITLE
Upgrade to fabric.js v3.6.3

### PR DESCRIPTION
**Pull request by tdiprima**
This upgrades fabric.adapted.js to the current version of fabric.js
A small portion of openseadragon-fabricjs-overlay.js has been updated accordingly.
demo.html has been modified so that the user can draw more than once, if desired.

If you could take a quick look :eyes: at the code, maybe try it out yourself, I'd appreciate it.

Thank you.

/cc @altert

### CODE REVIEW

**Comment by tdiprima** [comment]
I made some improvements and tested v3.6.3 lots.
Currently working on upgrading to fabric.js 4.0.0-rc1.

**Comment by altert** [comment]
Hello, Tammy

Thank you for your work on plugin!
You’ve closed your pull request bacause you want to move on to 4.0.0?



Alexey

**Comment by tdiprima** [comment]
Hi Alexey,

I just created a new pull request.  (plus a request for question #45)

Thanks very much :)

Tammy

**Comment by tdiprima** [comment]
And you're very welcome! :)

**Pull request closed without merging**
