### PR TITLE
Upgraded to fabric.js 4.0.0-rc.1

### PR DESCRIPTION
**Pull request by tdiprima**
Hi @altert!

Here is the updated version.  I also kept the 1.7.17 version and the 3.6.3 version in the `fabric` folder.
I looked at issue #25 , and added default scale options.  So we could probably close that one, if that's all that was required.
And I added `window.addEventListener('resize'...` to resize the fabric.js overlay when the window changes size.
And I updated demo.html.

Also, if you have any kind of hint/idea/comment for #45 , I'd appreciate it!

Cheers!!
Tammy

### CODE REVIEW

**Comment by altert** [comment]
Thanks! I’ve merged previous pull request dealing with static canvas. It conflicts with yours
https://github.com/altert/OpenseadragonFabricjsOverlay/pull/46/conflicts

It seems static canvas changes can be safely merged, but if you can, could you test your changes with static canvas PR changes?

Alexey

**Comment by tdiprima** [comment]
Hi Alexey,

Seems simple enough.  What is this modification for?  So that we can switch between regular fabric.js and using fabric.js + OpenSeadragon?  

If that's the case... then one of the things that comes up is -- let's say we don't add the script tag for openseadragon.js, because we're not using it.  Even though we're not using it, the plugin will still say: `requires OpenSeadragon`.  Because that's what this was written for. 😄   What are your thoughts?

Thanks,
Tammy

**Comment by altert** [comment]
modification is for static canvas - basically fabric without interactivity

Alexey

**Comment by tdiprima** [comment]
OK.  I tested it.  Works for me.

**Comment by tdiprima** [comment]
Would you like me to resolve the conflicts?  It asks if I want to go ahead and complete the merge, so that's why I wanted to check with you first.

**Comment by altert** [comment]
yes, sure, and then I’ll merge your pr

Alexey

**Comment by tdiprima** [comment]
It wouldn't save it without me committing the merge.  So, this is done.

**Comment by altert** [comment]
wait you’ve closed it - that means you want to change it? closed PR can’t be merged

Alexey

**Comment by tdiprima** [comment]
Hi @altert,

Ok sorry about that.  That was weird.  I re-opened the pull request.

Thanks,
Tammy

**Pull request merged**
